[project]
name = "julia-set"
version = "0.1.0"
description = "A Mandelbrot GUI explorer with JAX backend computation."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "imageio>=2.37.0",
    "jax==0.7.2",
    "matplotlib>=3.10.6",
    "numpy>=2.2.6",
    "pillow>=11.3.0",
]
